#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
============================================================================
 main_tracker.py — Surveillance Video Face Identification
============================================================================

 PURPOSE
 -------
 This is the core processing pipeline.  It reads an input CCTV-style
 video frame-by-frame, detects every face in each frame, compares each
 detected face against a database of pre-computed 128-d encodings
 (generated by `encode_faces.py`), and renders annotated bounding boxes:

   RED   box + name   →  verified match  (known prisoner)
   GREEN box + "Unknown" → no match found  (unregistered person)

 The processed video is simultaneously displayed on screen and (optionally)
 saved to disk as a new .mp4 file.

 TOLERANCE (SIMILARITY THRESHOLD)
 ────────────────────────────────
 The `--tolerance` parameter controls how strict the matching is.

   • Lower values (e.g. 0.45) → stricter matching, fewer false positives,
     but may miss true matches in poor-quality frames.  Recommended when
     False Acceptance Rate (FAR) must be minimised.

   • Higher values (e.g. 0.60) → more lenient, captures more true matches,
     but increases the risk of mis-identification.

   • Default: 0.50  — a balanced trade-off for cross-resolution scenarios
     (high-res mugshots vs. low-res surveillance footage).

 CROSS-RESOLUTION MATCHING NOTES
 ────────────────────────────────
 Surveillance cameras typically capture faces at much lower resolution
 than the mugshots used for enrolment.  To mitigate degradation:

   1. Frame up-scaling (optional): Before detection, the frame is resized
      by `--scale` factor.  Upscaling a 480p frame to ~720p can improve
      detection recall, at the cost of speed.

   2. Frame skipping: Processing every Nth frame (`--skip`) reduces
      computational load, enabling near-real-time playback on CPUs.

   3. Multi-sample enrolment: Using multiple mugshots per person
      (front, left, right profiles) in `encode_faces.py` builds a
      richer encoding set and improves recall at a given FAR.

 FALSE ACCEPTANCE RATE (FAR) TESTING
 ────────────────────────────────────
 After running the tracker, review the CSV log (`--log`) to compute:

   FAR = (# frames where an Unknown is labelled as Known) / (# total frames)

 Varying `--tolerance` across runs (0.40 → 0.60 in steps of 0.02) and
 plotting FAR vs. tolerance yields the system's ROC-like characteristic.

 USAGE
 -----
   python main_tracker.py -v input_videos/cctv_clip.mp4
   python main_tracker.py -v input_videos/cctv_clip.mp4 --tolerance 0.45
   python main_tracker.py -v input_videos/cctv_clip.mp4 --skip 3 --save
   python main_tracker.py -v input_videos/cctv_clip.mp4 --model cnn --scale 1.5 

============================================================================
"""

import os
import sys
import csv
import pickle
import argparse
import time
from datetime import datetime
from pathlib import Path

import cv2
from cv2 import dnn_superres
import numpy as np
import face_recognition
import imutils
from mtcnn import MTCNN

try:
    from tqdm import tqdm
except ImportError:
    tqdm = None


# ── Environment detection ───────────────────────────────────────────────────
def _has_display() -> bool:
    """Return True if a GUI display is available (False in Colab / SSH)."""
    import os
    # Google Colab sets COLAB_RELEASE_TAG or runs inside ipykernel
    if "COLAB_RELEASE_TAG" in os.environ or "COLAB_GPU" in os.environ:
        return False
    # Linux without DISPLAY
    if os.name == "posix" and not os.environ.get("DISPLAY"):
        return False
    return True


def _has_cuda_gpu() -> bool:
    """Return True if dlib was built with CUDA support and a GPU is available."""
    try:
        import dlib
        return dlib.DLIB_USE_CUDA and dlib.cuda.get_num_devices() > 0
    except Exception:
        return False


HEADLESS = not _has_display()
GPU_AVAILABLE = _has_cuda_gpu()


# ── Constants ───────────────────────────────────────────────────────────────
# Bounding box colours (BGR for OpenCV)
COLOR_MATCH = (0, 0, 255)       # RED   — known prisoner
COLOR_UNKNOWN = (0, 255, 0)     # GREEN — unregistered face
COLOR_TEXT_BG = (0, 0, 0)       # Black background behind text
FONT = cv2.FONT_HERSHEY_SIMPLEX
FONT_SCALE = 0.55
FONT_THICKNESS = 2
BOX_THICKNESS = 2


def parse_arguments() -> argparse.Namespace:
    """Parse CLI arguments."""
    ap = argparse.ArgumentParser(
        description="Identify known prisoners in surveillance video."
    )
    ap.add_argument(
        "-v", "--video",
        type=str,
        required=True,
        help="Path to the input CCTV video file (.mp4, .avi, etc.)",
    )
    ap.add_argument(
        "-e", "--encodings",
        type=str,
        default="encodings.pkl",
        help="Path to the serialised face-encodings pickle file (default: encodings.pkl)",
    )
    ap.add_argument(
        "-t", "--tolerance",
        type=float,
        default=0.50,
        help=(
            "Face-matching tolerance (lower = stricter). Range: 0.0–1.0. "
            "Default: 0.50.  Decrease to reduce FAR; increase to improve recall."
        ),
    )
    ap.add_argument(
        "-m", "--model",
        type=str,
        default="mtcnn",
        choices=["mtcnn", "hog", "cnn", "auto"],
        help=(
            "Face detection model.  Default: 'mtcnn' (MTCNN — robust to pose "
            "variation).  Legacy options 'hog', 'cnn', 'auto' are accepted "
            "but will still use MTCNN."
        ),
    )
    ap.add_argument(
        "--min-confidence",
        type=float,
        default=0.85,
        help=(
            "Minimum MTCNN detection confidence to accept a face (0.0–1.0). "
            "Default: 0.85.  Lower values increase recall at the cost of "
            "more false positive detections."
        ),
    )
    ap.add_argument(
        "-s", "--skip",
        type=int,
        default=3,
        help=(
            "Process every Nth frame for face detection (default: 3). "
            "Higher values speed up playback but may miss detections. "
            "Set to 1 for maximum accuracy."
        ),
    )
    ap.add_argument(
        "--scale",
        type=float,
        default=1.0,
        help=(
            "Scale factor for resizing frames before detection. "
            "Values > 1.0 upscale (better detection, slower). "
            "Values < 1.0 downscale (faster, may miss small faces). "
            "Default: 0.5 (half-res — good speed/accuracy trade-off)."
        ),
    )
    ap.add_argument(
        "--display-width",
        type=int,
        default=0,
        help=(
            "Width (px) of the display window.  "
            "Default: 0 (auto-fit to screen)."
        ),
    )
    ap.add_argument(
        "--save",
        action="store_true",
        help="Save the annotated output video to the output/ folder.",
    )
    ap.add_argument(
        "--log",
        type=str,
        default=None,
        help=(
            "Path to a CSV log file recording per-frame detections. "
            "Useful for FAR/FRR analysis.  Example: output/detections.csv"
        ),
    )
    ap.add_argument(
        "--enhance",
        action="store_true",
        help=(
            "Enable super-resolution pre-processing for low-resolution faces "
            "(IPD < 60 px).  Uses a lightweight ESPCN x4 model to hallucinate "
            "missing pixels before encoding, improving cross-resolution matching."
        ),
    )
    ap.add_argument(
        "--sr-model",
        type=str,
        default="ESPCN_x4.pb",
        help=(
            "Path to the OpenCV DNN Super-Resolution .pb weights file. "
            "Default: ESPCN_x4.pb (must be downloaded separately)."
        ),
    )
    return ap.parse_args()


def load_encodings(path: str) -> dict:
    """
    Load pre-computed face encodings from a pickle file.

    Parameters
    ----------
    path : str
        File path to the `.pkl` file generated by `encode_faces.py`.

    Returns
    -------
    dict
        {"encodings": list[np.ndarray], "names": list[str]}
    """
    if not os.path.exists(path):
        print(f"[ERROR] Encoding file not found: {path}")
        print("        Run  `python encode_faces.py`  first.")
        sys.exit(1)

    with open(path, "rb") as f:
        data = pickle.load(f)

    n_enc = len(data.get("encodings", []))
    n_names = len(set(data.get("names", [])))
    print(f"[INFO] Loaded {n_enc} encoding(s) for {n_names} person(s) from '{path}'.")
    return data


def identify_faces(
    face_encodings: list[np.ndarray],
    known_encodings: list[np.ndarray],
    known_names: list[str],
    tolerance: float,
) -> list[str]:
    """
    Match each detected face encoding against the known database.

    For each query encoding, we compute the Euclidean distance to every
    known encoding.  If the minimum distance is below `tolerance`, the
    face is labelled with the most-voted name (majority voting across
    all matches).  Otherwise it is labelled "Unknown".

    Parameters
    ----------
    face_encodings : list of np.ndarray
        128-d encodings from the current frame.
    known_encodings : list of np.ndarray
        Reference encodings from the database.
    known_names : list of str
        Corresponding labels for `known_encodings`.
    tolerance : float
        Maximum Euclidean distance to accept a match (0.0–1.0).

    Returns
    -------
    list of (str, float)
        Predicted name (or "Unknown") and confidence for each face.
    """
    results: list[tuple[str, float]] = []

    for encoding in face_encodings:
        # Compare against every known face
        distances = face_recognition.face_distance(known_encodings, encoding)
        matches = distances <= tolerance

        name = "Unknown"

        if np.any(matches):
            # Majority-vote among all matches
            matched_names = [known_names[i] for i, m in enumerate(matches) if m]
            # Weight by inverse distance for tie-breaking
            name_counts: dict[str, float] = {}
            for i, m in enumerate(matches):
                if m:
                    n = known_names[i]
                    # Add inverse-distance weight (closer = higher weight)
                    weight = 1.0 / (distances[i] + 1e-6)
                    name_counts[n] = name_counts.get(n, 0.0) + weight

            name = max(name_counts, key=name_counts.get)

            # Also report confidence (1 - min_distance) — useful for logs
            best_dist = min(distances[matches])
            confidence = round(1.0 - best_dist, 3)
        else:
            confidence = 0.0

        results.append((name, confidence))

    return results


def draw_annotation(
    frame: np.ndarray,
    top: int, right: int, bottom: int, left: int,
    name: str,
    confidence: float,
) -> None:
    """Draw a bounding box and label on the frame (in-place)."""
    is_known = name != "Unknown"
    color = COLOR_MATCH if is_known else COLOR_UNKNOWN

    # Bounding box
    cv2.rectangle(frame, (left, top), (right, bottom), color, BOX_THICKNESS)

    # Label text
    if is_known:
        label = f"{name} ({confidence:.0%})"
    else:
        label = "Unknown"

    # Text background rectangle
    (tw, th), _ = cv2.getTextSize(label, FONT, FONT_SCALE, FONT_THICKNESS)
    cv2.rectangle(
        frame,
        (left, bottom),
        (left + tw + 10, bottom + th + 14),
        color,
        cv2.FILLED,
    )
    # Text
    cv2.putText(
        frame,
        label,
        (left + 5, bottom + th + 8),
        FONT,
        FONT_SCALE,
        (255, 255, 255),
        FONT_THICKNESS,
    )


def process_video(args: argparse.Namespace, data: dict) -> None:
    """
    Main video processing loop.

    Reads the input video, runs face detection + recognition on selected
    frames, annotates results, and optionally saves the output.

    Works in two modes:
      • GUI mode (local)   — shows a live window, press 'q' to quit.
      • Headless mode (Colab / SSH) — auto-saves output, shows progress bar.
    """
    known_encodings = data["encodings"]
    known_names = data["names"]

    # ── Resolve 'auto' model selection ──────────────────────────────────
    if args.model == "auto":
        args.model = "cnn" if GPU_AVAILABLE else "hog"

    # ── Initialise super-resolution model (once, outside the frame loop) ─
    sr = None
    if args.enhance:
        try:
            sr = dnn_superres.DnnSuperResImpl_create()
            sr.readModel(args.sr_model)
            sr.setModel("espcn", 4)
            print(f"[INFO] Super-Resolution enabled  (model={args.sr_model}, scale=4x)")
        except Exception as e:
            print(f"[ERROR] Failed to load SR model '{args.sr_model}': {e}")
            print("        Download it with:")
            print("        curl -L -o ESPCN_x4.pb https://raw.githubusercontent.com/fannymonori/TF-ESPCN/master/export/ESPCN_x4.pb")
            sys.exit(1)

    # ── Initialise face detector (once, outside the frame loop) ────────
    use_mtcnn = (args.model == "mtcnn")
    mtcnn_detector = None
    if use_mtcnn:
        mtcnn_detector = MTCNN()
        print(f"[INFO] MTCNN detector initialised  (min_confidence={args.min_confidence})")
    else:
        print(f"[INFO] Using face_recognition model: {args.model.upper()}")

    # ── Open video capture ──────────────────────────────────────────────
    cap = cv2.VideoCapture(args.video)
    if not cap.isOpened():
        print(f"[ERROR] Cannot open video: {args.video}")
        sys.exit(1)

    fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    print(f"[INFO] Video : {args.video}")
    print(f"[INFO] Resolution : {width}×{height} @ {fps:.1f} FPS")
    print(f"[INFO] Total frames : {total_frames}")
    print(f"[INFO] Frame skip : every {args.skip} frame(s)")
    print(f"[INFO] Tolerance : {args.tolerance}")
    print(f"[INFO] Detection model : {args.model.upper()}")
    if use_mtcnn:
        print(f"[INFO] MTCNN min conf  : {args.min_confidence}")
    print(f"[INFO] Scale factor : {args.scale}")
    print(f"[INFO] SR enhance   : {'ON (IPD < 60 px)' if args.enhance else 'OFF'}")
    print(f"[INFO] Headless mode : {'Yes (no display)' if HEADLESS else 'No (GUI)'}")
    print()

    # ── Video writer (optional — forced on in headless mode) ────────────
    writer = None
    out_path = None
    if args.save or HEADLESS:
        os.makedirs("output", exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        out_path = os.path.join("output", f"tracked_{timestamp}.mp4")
        fourcc = cv2.VideoWriter_fourcc(*"mp4v")
        writer = cv2.VideoWriter(out_path, fourcc, fps, (width, height))
        print(f"[INFO] Saving output → {out_path}")

    # ── CSV log (optional) ──────────────────────────────────────────────
    csv_file = None
    csv_writer = None
    if args.log:
        os.makedirs(os.path.dirname(args.log) or ".", exist_ok=True)
        csv_file = open(args.log, "w", newline="", encoding="utf-8")
        csv_writer = csv.writer(csv_file)
        csv_writer.writerow([
            "frame_no", "timestamp_sec", "face_id",
            "name", "confidence",
            "top", "right", "bottom", "left",
        ])
        print(f"[INFO] Logging detections → {args.log}")

    # ── Progress bar (headless) / instructions (GUI) ────────────────────
    pbar = None
    if HEADLESS and tqdm is not None and total_frames > 0:
        pbar = tqdm(total=total_frames, desc="Processing", unit="frame")
    elif not HEADLESS:
        print("[INFO] Press 'q' to quit.\n")
    # ── Processing loop ─────────────────────────────────────────────────
    frame_no = 0
    faces_detected_total = 0
    matches_total = 0
    processing_times: list[float] = []

    # Cache the most recent detections for skipped frames
    cached_boxes: list[tuple] = []
    cached_results: list[tuple] = []

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        frame_no += 1
        t0 = time.time()

        if pbar is not None:
            pbar.update(1)

        # ── Determine whether to run detection on this frame ────────
        run_detection = (frame_no % args.skip == 0) or (frame_no == 1)

        if run_detection:
            # Optionally scale for better detection on low-res footage
            if args.scale != 1.0:
                proc_frame = cv2.resize(
                    frame, None,
                    fx=args.scale, fy=args.scale,
                    interpolation=cv2.INTER_LINEAR,
                )
            else:
                proc_frame = frame

            # Convert BGR → RGB for detection and encoding
            rgb = cv2.cvtColor(proc_frame, cv2.COLOR_BGR2RGB)

            # Detect face locations
            if use_mtcnn:
                # MTCNN detection (min_face_size passed as stage kwarg).
                # Wrapped in try/except: ONet can crash with a ValueError
                # on frames where no candidates survive PNet/RNet.
                try:
                    detections = mtcnn_detector.detect_faces(rgb, min_face_size=20)
                except ValueError:
                    detections = []

                # Convert MTCNN [x, y, w, h] → (top, right, bottom, left)
                # and apply confidence filter
                boxes = []
                for face in detections:
                    if face["confidence"] < args.min_confidence:
                        continue
                    x, y, w, h = face["box"]
                    # MTCNN can occasionally return negative offsets; clamp to 0
                    x, y = max(0, x), max(0, y)
                    top   = y
                    right = x + w
                    bottom = y + h
                    left  = x
                    boxes.append((top, right, bottom, left))
            else:
                # Legacy HOG / CNN fallback via face_recognition
                boxes = face_recognition.face_locations(rgb, model=args.model)

            # Scale boxes back to original frame coordinates
            if args.scale != 1.0 and boxes:
                inv = 1.0 / args.scale
                boxes = [
                    (
                        int(t * inv),
                        int(r * inv),
                        int(b * inv),
                        int(l * inv),
                    )
                    for (t, r, b, l) in boxes
                ]

            # Compute encodings for detected faces (reuse rgb on original frame)
            rgb_full = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB) if (args.scale != 1.0) else rgb

            # ── Super-Resolution conditional pipeline ───────────────
            face_encodings = []
            for box in boxes:
                top_b, right_b, bottom_b, left_b = box
                face_w = right_b - left_b
                face_h = bottom_b - top_b

                if sr is not None and face_w < 60:
                    # Crop the low-res face from the RGB frame
                    face_crop = rgb_full[
                        max(0, top_b):bottom_b,
                        max(0, left_b):right_b,
                    ]
                    # Hallucinate missing pixels with ESPCN x4
                    upscaled_face = sr.upsample(face_crop)
                    up_h, up_w = upscaled_face.shape[:2]
                    print(
                        f"[SR] Enhanced {face_w}x{face_h} face "
                        f"to {up_w}x{up_h}"
                    )
                    # Encode on the upscaled crop (full-image coords)
                    enc = face_recognition.face_encodings(
                        upscaled_face,
                        known_face_locations=[(0, up_w, up_h, 0)],
                    )
                else:
                    # Standard encoding from the full frame
                    enc = face_recognition.face_encodings(
                        rgb_full,
                        known_face_locations=[box],
                    )

                if enc:
                    face_encodings.append(enc[0])
            # ── End SR pipeline ─────────────────────────────────────

            # Identify each face
            if face_encodings:
                results = identify_faces(
                    face_encodings, known_encodings, known_names, args.tolerance
                )
            else:
                results = []

            # Update cache
            cached_boxes = boxes
            cached_results = results

        # ── Draw annotations (using cached results for skipped frames) ─
        for idx, ((top, right, bottom, left), (name, conf)) in enumerate(
            zip(cached_boxes, cached_results)
        ):
            draw_annotation(frame, top, right, bottom, left, name, conf)

            # Stats
            if run_detection:
                faces_detected_total += 1
                if name != "Unknown":
                    matches_total += 1

                # CSV logging
                if csv_writer:
                    csv_writer.writerow([
                        frame_no,
                        round(frame_no / fps, 3),
                        idx,
                        name,
                        conf,
                        top, right, bottom, left,
                    ])

        # ── HUD overlay ─────────────────────────────────────────────
        elapsed = time.time() - t0
        processing_times.append(elapsed)

        avg_fps = (
            len(processing_times[-30:]) / sum(processing_times[-30:])
            if processing_times
            else 0.0
        )

        hud_lines = [
            f"Frame: {frame_no}/{total_frames}",
            f"Faces: {len(cached_boxes)}",
            f"FPS: {avg_fps:.1f}",
            f"Tol: {args.tolerance}",
        ]
        for i, line in enumerate(hud_lines):
            cv2.putText(
                frame, line,
                (10, 25 + i * 22),
                FONT, 0.50, (255, 255, 255), 1, cv2.LINE_AA,
            )

        # ── Write / display ─────────────────────────────────────────
        if writer:
            writer.write(frame)

        if not HEADLESS:
            # Fit to screen: auto-compute display width on first frame
            if not hasattr(process_video, "_win_created"):
                win_name = "Face Identification — Surveillance Feed"
                cv2.namedWindow(win_name, cv2.WINDOW_NORMAL)
                if args.display_width > 0:
                    disp_w = args.display_width
                    disp_h = int(height * (disp_w / width))
                else:
                    # Fit to ~90 % of screen height
                    try:
                        screen_h = cv2.getWindowImageRect(win_name)[3]
                    except Exception:
                        screen_h = 0
                    if screen_h <= 0:
                        screen_h = 720          # safe fallback
                    disp_h = int(screen_h * 0.9)
                    disp_w = int(width * (disp_h / height))
                cv2.resizeWindow(win_name, disp_w, disp_h)
                process_video._win_created = True
                process_video._win_name = win_name

            cv2.imshow(process_video._win_name, frame)

            # 'q' to quit
            key = cv2.waitKey(1) & 0xFF
            if key == ord("q"):
                print("[INFO] User requested exit.")
                break

    # ── Cleanup ─────────────────────────────────────────────────────────
    if pbar is not None:
        pbar.close()
    cap.release()
    if writer:
        writer.release()
    if csv_file:
        csv_file.close()
    if not HEADLESS:
        cv2.destroyAllWindows()

    # ── Summary ─────────────────────────────────────────────────────────
    print()
    print("=" * 55)
    print(" Processing Summary")
    print("=" * 55)
    print(f"  Frames processed  : {frame_no}")
    print(f"  Faces detected    : {faces_detected_total}")
    print(f"  Known matches     : {matches_total}")
    print(f"  Unknown faces     : {faces_detected_total - matches_total}")
    if processing_times:
        avg = sum(processing_times) / len(processing_times)
        print(f"  Avg detect time   : {avg * 1000:.1f} ms/frame")
        print(f"  Effective FPS     : {1.0 / avg:.1f}")
    print("=" * 55)

    if HEADLESS and out_path:
        print(f"\n[INFO] Output video saved to: {out_path}")
        print("       Download it from the Colab file browser or run:")
        print(f"       from google.colab import files; files.download('{out_path}')")


# ── Main ────────────────────────────────────────────────────────────────────
def main() -> None:
    args = parse_arguments()

    print("=" * 55)
    print(" Surveillance Video Face Identification")
    print("=" * 55 + "\n")

    data = load_encodings(args.encodings)
    process_video(args, data)

    print("\n[INFO] Done.\n")


if __name__ == "__main__":
    main()
